### ISSUE TITLE
Multiwrite through multifeed?

### ISSUE THREAD

**Issue by rjmackay** [RangerMauve/hyperbeedeebee#1]
Would it be possible to use https://github.com/kappa-db/multifeed or something similar to add multi-writer support?
Would that break any key assumptions in hyperbeedeebee?

**Comment by RangerMauve** [comment]
Multifeed is going to be harder to get working with existing hypercore-protocol stuff, as well the kappa-style indexing would break the sparseness.

I was however considering making a module for multi-writer hyperbee that uses a similar architecture to co-hyperdrive: https://github.com/RangerMauve/co-hyperdrive

**Comment by RangerMauve** [comment]
Gonna close this for now. If folks want multiwriter, they can figure it out at the hyperbee level (maybe with autobase?) and pass an hyperbee-compatible interface to this library for actually performing reads and writes.
