### ISSUE TITLE
Unable to sort by index that is not at field position 0

### ISSUE THREAD

**Issue by hexadecible** [RangerMauve/hyperbeedeebee#5]
It appears that if you create a new index with an array of fields, and then try to sort that collection by any field that is not at index 0, the query will break.

```js
await db.collection('example').createIndex(['createdAt', 'example'])

await db.collection('example').insert({ example: 1, createdAt: new Date() })
await db.collection('example').insert({ example: 2, createdAt: new Date() })
await db.collection('example').insert({ example: 3, createdAt: new Date() })

const docs1 = await db.collection('example').find().sort('createdAt', -1) // Works
const docs2 = await db.collection('example').find().sort('example', -1) // This does not work
```

**Comment by RangerMauve** [comment]
Sadly, that's a limitation of how B+ trees and indexes work and is by design. You can't sort by a field that isn't at index 0 because the B+ tree only sorts by the prefix of the key. If there are other fields you need to sort them by then you'll need to have more indexes. 😁
