### ISSUE TITLE
Account for BSON encoding lower bits from int64

### ISSUE THREAD

**Issue by RangerMauve** [RangerMauve/hyperbeedeebee#6]
int64 data (like Dates, or Longs) is currently encoded with the lower bits first (e.g. 4 lowest bytes, then 4 highest bytes). [source](https://github.com/mongodb/js-bson/blob/main/src/parser/serializer.ts#L188)

This is pretty much the exact opposite of what we need.

This breaks ordered searching in indexes. We've glossed over this by having dates created quickly enough in tests that usually only the lowest of the low bits would change within the span of the test.

I think we're going to need to ditch BSON for the key generation and jump into custom logic. 🤷

This'll require a breaking change.

**Comment by omarbadran** [comment]
You can use [CBOR](https://www.npmjs.com/package/cbor) for encoding/decoding and [ulid](https://www.npmjs.com/package/ulid) instead of ObjectID for the IDs.

**Comment by RangerMauve** [comment]
Good point, I was considering using CBOR for an IPLD based database down the line so now might be a useful time to look into it.

Though given the strong dependency on BSON for existing data we might just use it for the index key generation logic. 🤔

**Comment by omarbadran** [comment]
If you already have data stored in BSON format just build a simple key generation logic instead.

Also, why a database on IPFS? There is already a lot of solutions out there like ThreadDB from textile.io, and OrbitDB. I'm not familiar with the IPFS ecosystem but it seems that these databases don't support sparse replication or real-time updates like the ones built on hypercore. The append-only log they use is very basic compared to hypercore and the user has to download all the data before being able to interact with it. Unless you are ready to write a shit ton of code it won't be that easy to build.

What benefits do you think it brings compared to solutions based on hypercore?

**Comment by RangerMauve** [comment]
> Also, why a database on IPFS?

Yeah all the existing IPFS databases are based on append only logs and aren't using stuff like hyperbee to pre-index data.

I'm gonna be making a new database once we standardize [prolly trees](https://github.com/ipfs/devgrants/pull/194) which are like Hyperbee's B+ tree, but with the ability to determenistically merge a bunch of them togehter.

This means that you can avoid having to query each users's hyperbee individually and can instead combine a bunch of data sources into one and sparsely query them. 😁

This is probably a Q2 2023 thing and there's a bunch of stuff that needs to be done before that.

**Comment by omarbadran** [comment]
looks very promising!

So much stuff going on in the p2p world. I'm a web developer who got interested in this a few months ago and the amount of new information in this space is giving me a headache.

I'm building a database on top of hypercore, similar to yours, but without the concept of collections (available as a module), and the API will mimic [Redis](https://github.com/redis/redis-om-node#-redis-om-for-nodejs). Each index, collection, computed view, etc. is stored on a different bee. It will give me some advantages, such as complex access control and better performance in collaborative environments. For example, a computed view can have different read/write permissions than another computed view from the same database.

And each database is referenced by one core that will store the metadata such access control list, a list of peers who subscribed to events from this database, and a list of seeding servers to retrieve the data faster, and fallback to use hyperswarm in case any of the centralized servers can't be reached..

**Comment by omarbadran** [comment]
Here is my miserable attempt at making at database: https://github.com/omarbadran/hydra

No collections and no compound indexes, although both can be done with few changes. Using CBOR for documents and [charwise](https://www.npmjs.com/package/charwise) for key generation. I faced some problems with CBOR and was too lazy to fix them, charwise is simple and gets the job done.

Performance wise, 10k documents with two indexes (numeric & string) take about 5 seconds to insert, and 3ms to query one document using an indexed field. Currently supported operations are `$eq` `$gt` `$lt` `$gte` `$lte` `$between` `$betweenInclusive` `$containAll` and `$containAny`

mongoDB is about 30x faster in inserts, so I wouldn't bother using it for anything serious 🥲

**Comment by RangerMauve** [comment]
That's awesome! Good work. If you wanna chat databases more, I'm usually around in the Agregore Matrix channel. https://matrix.to/#/#agregore:mauve.moe

Also, I've released the new code in 2.0.0. Old indexes will get auto-upgraded to the new version so watch out!
